using System;
using System.Text.Json;
using System.Collections.Generic;

namespace AeroToolsUNLP.Services.Calculators
{
    public class GeometriaService
    {
        public string GenerateRectangleEntity(double lon, double lat, double width, double height, double extrusion, string color = "red")
        {
            // Simplified rectangle approximation for demo
            // In real Cesium, we pass degrees. 
            // Here we just prepare the JSON for the JS helper.
            
            var options = new
            {
                name = "Volume 1",
                polygon = new
                {
                    hierarchy = new 
                    {
                        positions = new[] 
                        {
                            new { x = lon - width/2, y = lat - height/2, z = 0 }, // Simplified cartesian, need cartographic degrees usually
                            // Actually Cesium entity API expects specific structure. 
                            // Let's use Cartesian3.fromDegrees in JS side or providing degrees array here.
                        }
                    },
                    height = 0,
                    extrudedHeight = extrusion,
                    material = color,
                    outline = true,
                    outlineColor = "black"
                },
                 // Let's try a cylinder as it is easier to param via center + radius
                cylinder = new 
                {
                    length = extrusion,
                    topRadius = width,
                    bottomRadius = width,
                    material = color,
                    outline = true
                },
                position = new { lon = lon, lat = lat, height = extrusion / 2 } // Position for cylinder center
            };

            // For the customized JS helper, we will send a specific structure that our helper understands 
            // OR standard Cesium Entity JSON if we map it correctly.
            // Let's stick to the Cylinder for 'Surface Generator' as Obstacle for now (easier to implement cleanly)
            
            var entity = new 
            {
               position = new { 
                   cartographicDegrees = new[] { lon, lat, extrusion / 2.0 } 
               },
               cylinder = new {
                   length = extrusion,
                   topRadius = width,
                   bottomRadius = width,
                   material = color,
                   outline = true
               }
            };
            
            // NOTE: The JS helper 'addEntity' takes options. 
            // But 'position' needs to be a Cartesian3. 
            // We need to parse this on JS side. 
            // Let's pass a specific custom DTO that our helper interprets.
            
            return JsonSerializer.Serialize(entity);
        }
        
        public string GenerateKml(double lon, double lat, double radius, double height, string name)
        {
            // Simple KML generation
            return $@"<?xml version=""1.0"" encoding=""UTF-8""?>
<kml xmlns=""http://www.opengis.net/kml/2.2"">
  <Placemark>
    <name>{name}</name>
    <description>Obstacle generated by AeroTools UNLP</description>
    <Point>
      <coordinates>{lon},{lat},{height}</coordinates>
    </Point>
  </Placemark>
</kml>";
        }
    }
}
